### ISSUE TITLE
无法build

### ISSUE THREAD

**Issue by mingyEx** [L-Sun/HitagiEngine#3]
>在.vscode/settings.json中修改E:/workspace/vcpkg为你所安装Vcpkg的具体路径

但是[此文件](https://github.com/L-Sun/HitagiEngine/blob/dev/.vscode/settings.json)里没有可以被修改的 `E:/workspace/vcpkg` ,且，为何不添加`*sln`来直接支持visual studio打开呢？

**Comment by L-Sun** [comment]
README好久没更新了，settings.json中加入这个

```json
    "cmake.configureArgs": [
        "-DCMAKE_TOOLCHAIN_FILE=/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake"
    ]
```

至于第二个问题，因为我更倾向在各个平台上coding的体验是一致的，所以并没有使用visual studio。不过你可以使用CMake-GUI生成`sln`项目文件，或者参考 [CMake projects in Visual Studio](https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170)

**Comment by L-Sun** [comment]
因为是使用vcpkg 的 manifest 模式，所以**不用额外**运行
```bash
vcpkg.exe install --triplet x64-windows crossguid zlib libjpeg-turbo libpng assimp freetype fmt spdlog gtest
```

**Comment by L-Sun** [comment]
此外，你需要安装 ISPC 编译器来保证数学库的编译。[下载地址 Intel SPMD Program Compiler](https://github.com/ispc/ispc/releases/tag/v1.17.0)。需要确保`ispc.exe`在 环境变量 PATH 中
